### ISSUE TITLE
Add Astro policy behaviour

### ISSUE THREAD

**Issue by anavc97** [JoaninhaRaposo/overcooked_ai#11]

**Comment by anavc97** [comment]
coordenates are switched (ex. ball is in (8,1) in overcooked_gym -> ball is in (1,8) in overcooked_mdp

**Comment by anavc97** [comment]
movement from A to B: need to add A* search to find best direction for next action

**Comment by JoaninhaRaposo** [comment]
22 fev - 1ª tentativa de implementação - Ainda nao terminado
1) Comparação feita com o overcooked-gym 
2) Tentativa de implementação semelhante - por terminar - acabar a a_joint e função action do DummyAI() (tentar usar action from policy do yaaf)

**Comment by JoaninhaRaposo** [comment]
BUG: Quando Humano pega numa bola e coloca somewhere noutro balcao: Estado do environment diz que astro esta a pegar nessa bola.

**Comment by JoaninhaRaposo** [comment]
state_converter: Alterado de acordo com o OvercookedGym. Astro continua com mesmas ações anteriores.

**Comment by JoaninhaRaposo** [comment]
action converter: Alterado de acordo com overcooked gym (exceto ice slip & ir ter com o humano). Comportamento do astro mudou, mas ainda não está correto -> Verificar questao das pos trocadas.

**Comment by JoaninhaRaposo** [comment]
Update: Alterei o self.dist para ser 100 quando não está nas bancadas (tal como no  AstroHandCoded)
Para a reunião: Dúvidas sobre move do astro nesta situação (AstroHandCoded: Vai para node da onion + perto, no smart não)
Dist nunca é menor que 1 (?)

**Comment by JoaninhaRaposo** [comment]
27/03: Astro já parece ter o comportamento "normal" 
Mas às vezes fica parado nos nós em vez de agir.

**Comment by JoaninhaRaposo** [comment]
Comparação com overcooked gym -> é estranho o astro parar tanta vez
Nova conclusao: O Astro funciona bem, ate que lhe e colocado uma bola dentro

**Comment by JoaninhaRaposo** [comment]
Problema encontrado (e já resolvido): O indice das onions nao estava correto.
