### ISSUE TITLE
Change menu on top of the page to not have all the options

### ISSUE THREAD

**Issue by JoaninhaRaposo** [JoaninhaRaposo/overcooked_ai#12]

**Comment by JoaninhaRaposo** [comment]
Ficheiro index.html (overcooked-demo/static/templates):
->Caixas a mais - eliminado
->Título da pagina, mudado para Toxic Waste Game
-> Join existent game button apagado
-> ~~TODO LATER: Apagar instruções, tutorial (criar novas paginas so com essas opções)~~

Ficheiro bootstrap.min.css (overcooked-demo/static/css):
-> Caixa com (Player 1, Player 2, layout) -> alterado o padding no container, left e right, de 15px, 15 px para 250px e 0px, para centralizar as caixas no topo da pagina
(.container{margin-right:auto;margin-left:auto;padding-left:250px;padding-right:0px})

~~TODO LATER: Caixas terem opções já especificadas (Ou apagar?)~~

~~TODO LATER: Apagar opções Leave durante os niveis~~

~~TODO(not that later): Quando o jogo acaba, não aparecer o botão de criar jogo~~
Done: ficheiro index.js (overcooked-demo/server/static/js)
Alterado: socket.on('end_game', function(data)

**Comment by JoaninhaRaposo** [comment]
@anavc97 A opção "Leave" durante o jogo, removemos?

**Comment by anavc97** [comment]
> @anavc97 A opção "Leave" durante o jogo, removemos?

Sim, pelo menos do nivel 1 e 2
