### ISSUE TITLE
Game Over screen

### ISSUE THREAD

**Issue by JoaninhaRaposo** [JoaninhaRaposo/overcooked_ai#13]

**Comment by JoaninhaRaposo** [comment]
@anavc97 o que pretendes que o game over screen tenha? Texto a dizer game over + pontuação final?

**Comment by anavc97** [comment]
> @anavc97 o que pretendes que o game over screen tenha? Texto a dizer game over + pontuação final?

Sim, isso deve chegar

**Comment by JoaninhaRaposo** [comment]
Changes: created function drawGameOver, changed score, alter graphics_end (com "batota" para funcionar)
Talvez seja preciso mudanças?
