### ISSUE TITLE
Add "ice" terrain

### ISSUE THREAD

**Issue by JoaninhaRaposo** [JoaninhaRaposo/overcooked_ai#5]

**Comment by JoaninhaRaposo** [comment]
Ice is currently showing in the correct position. However, it is stated as an object (like the onions, on the graphics from overcooked-demo); So, the agents can not walk over them; Need to change the graphics file;

**Comment by anavc97** [comment]
@JoaninhaRaposo tenta adicionar alguma cena ao _terrain_to_img_ (line 148 do _overcooked_graphics_)

**Comment by JoaninhaRaposo** [comment]
Já descobri porque não funciona: Debaixo do gelo ele está a colocar bancadas.

**Comment by JoaninhaRaposo** [comment]
Mecânica do gelo: overcooked_mdp (overcooked_ai), funcao get_valid_player_positions
